---
- hosts: web
  remote_user: root

  tasks:
  - name: Download and install httpd pkgs
    yum: name=httpd state=present
    

  - name: Active service httpd
    service: name=httpd state=started enabled=yes
