---
- hosts: web
  remote_user: root
  vars_files:
    - vars/httpd_vars.yml

  tasks:
  - name: Copying content
    copy: src=templates/{{ item }} dest={{ http_documentroot }}/{{ item }}
    with_items:
    
    - index.html
    
