---
- hosts: lb
  remote_user: root
  vars_files:
    - vars/httpd_vars.yml

  tasks:
  - name: Applying configuration Full
    copy: src=file/{{ item }} dest=/etc/haproxy/{{ item }}
    with_items:
    - haproxy.cfg
    

  - name: Reloading config
    service: name=haproxy state=reloaded
