---
- hosts: lb
  remote_user: root
  vars_files:
    - vars/httpd_vars.yml

  tasks:
  - name: Applying configuration Full
    copy: src=file/haproxy.cfg dest=/etc/haproxy/haproxy
    
    

  - name: Reloading config
    service: name=haproxy state=reloaded
